spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heytea?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: zyr123